-- Migration 0028: Voting Register Snapshots (MEM-006 §02.11)
--
-- Immutable AGM snapshots. Once a row is inserted it is never updated --
-- this is an append-only audit record of who was eligible to vote at a
-- given moment in time.
--
-- Quorum formula stored here is a SNAPSHOT of the value at generation
-- time. Governance may change the quorum fraction later; historical
-- snapshots keep the original computation.
--
-- MEM-006 voting-eligible classes (HARD): Full Member, Life Member,
-- Patron Member, Founding Member. ACTIVE state only. No other class,
-- group type, recognition level, or RBAC role confers voting rights.

CREATE TABLE voting_register_snapshots (
  id                   INT UNSIGNED   NOT NULL AUTO_INCREMENT,
  uuid                 CHAR(36)       NOT NULL,
  label                VARCHAR(255)   NOT NULL COMMENT 'Human label e.g. "AGM July 2026"',
  generated_by_user_id BIGINT         NULL     COMMENT 'NULL if generated by system job',
  eligible_count       SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  quorum_threshold     SMALLINT UNSIGNED NOT NULL DEFAULT 0
    COMMENT 'ceil(eligible_count / 3) at generation time -- standard 1/3 quorum',
  snapshot_json        MEDIUMTEXT     NOT NULL
    COMMENT 'JSON array: [{membership_id, membership_number, user_id, full_name, class_code, activated_at}]',
  generated_at         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_vrs_uuid (uuid),
  KEY idx_vrs_generated_at (generated_at DESC),
  CONSTRAINT fk_vrs_actor
    FOREIGN KEY (generated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Immutable AGM voting register snapshots (MEM-006 §02.11)';
