/**
 * scripts/backfill_photo_dimensions.mjs
 *
 * Finds photos with null width_px/height_px in the DB (via the production API),
 * reads JPEG/PNG dimensions from the image binary, and prints UPDATE SQL to stdout.
 *
 * Usage (run locally, targets production API):
 *   node scripts/backfill_photo_dimensions.mjs
 *
 * Then apply the generated SQL on the production server:
 *   mysql -u bcc_v3_app -p<pass> bcc_v3 < /tmp/fix_dims.sql
 *
 * Requires Node.js 18+ (native fetch).
 */

const API_BASE = 'https://v3bcc.bhopal.info/api/v1';

// ── JPEG dimension reader ──────────────────────────────────────────────────
// Reads the SOF (Start of Frame) marker from a partial JPEG buffer.
function jpegDimensions(buf) {
  let i = 0;
  if (buf[0] !== 0xFF || buf[1] !== 0xD8) return null; // not JPEG
  i = 2;
  while (i < buf.length - 9) {
    if (buf[i] !== 0xFF) break;
    const marker = buf[i + 1];
    const segLen = (buf[i + 2] << 8) | buf[i + 3];
    // SOF markers: 0xC0..0xC3, 0xC5..0xC7, 0xC9..0xCB, 0xCD..0xCF
    if ((marker >= 0xC0 && marker <= 0xCF) && marker !== 0xC4 && marker !== 0xC8 && marker !== 0xCC) {
      const height = (buf[i + 5] << 8) | buf[i + 6];
      const width  = (buf[i + 7] << 8) | buf[i + 8];
      return { width, height };
    }
    i += 2 + segLen;
  }
  return null;
}

// ── PNG dimension reader ───────────────────────────────────────────────────
function pngDimensions(buf) {
  // PNG signature: 8 bytes, then IHDR chunk at offset 8
  if (buf.length < 24) return null;
  const sig = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];
  for (let i = 0; i < 8; i++) if (buf[i] !== sig[i]) return null;
  const width  = (buf[16] << 24) | (buf[17] << 16) | (buf[18] << 8) | buf[19];
  const height = (buf[20] << 24) | (buf[21] << 16) | (buf[22] << 8) | buf[23];
  return { width, height };
}

async function getImageDimensions(url) {
  // Try partial range first (fast — only first 64 KB)
  let res = await fetch(url, { headers: { Range: 'bytes=0-65535' } });
  if (res.status === 400 || res.status === 416) {
    // ImageKit doesn't support Range on this file — fetch without Range
    // but abort the stream once we have enough bytes
    res = await fetch(url);
  }
  if (!res.ok && res.status !== 206) throw new Error(`HTTP ${res.status}`);

  // Read up to 128 KB from the response stream to find SOF/IHDR
  const reader = res.body.getReader();
  const chunks = [];
  let total = 0;
  const MAX_BYTES = 131072; // 128 KB
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
    total += value.length;
    if (total >= MAX_BYTES) { reader.cancel(); break; }
  }
  const buf = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) { buf.set(chunk, offset); offset += chunk.length; }
  return jpegDimensions(buf) ?? pngDimensions(buf) ?? null;
}

async function main() {
  // 1. Fetch all photographers
  const phRes  = await fetch(`${API_BASE}/photographers?limit=500`);
  const phData = await phRes.json();
  const photographers = phData.data ?? [];

  const sqls = [];

  for (const ph of photographers) {
    const userId = ph.id;
    const photosRes  = await fetch(`${API_BASE}/gallery/photographer/${userId}?limit=500`);
    const photosData = await photosRes.json();
    const photos     = photosData.photos ?? [];

    const nullDim = photos.filter(p => !p.width_px || !p.height_px);
    if (!nullDim.length) continue;

    process.stderr.write(`${ph.username}: ${nullDim.length} photos need dimensions\n`);

    for (const photo of nullDim) {
      const url = photo.urls?.original ?? photo.urls?.medium;
      if (!url) {
        process.stderr.write(`  ${photo.uuid}: no URL — skipping\n`);
        continue;
      }
      try {
        const dims = await getImageDimensions(url);
        if (!dims) {
          process.stderr.write(`  ${photo.uuid}: could not read dimensions\n`);
          continue;
        }
        process.stderr.write(`  ${photo.uuid}: ${dims.width}×${dims.height}\n`);
        sqls.push(
          `UPDATE photos SET width_px = ${dims.width}, height_px = ${dims.height} WHERE uuid = '${photo.uuid}';`
        );
      } catch (err) {
        process.stderr.write(`  ${photo.uuid}: error — ${err.message}\n`);
      }
    }
  }

  if (!sqls.length) {
    process.stderr.write('No updates needed.\n');
    return;
  }

  // Output SQL to stdout for piping or manual application
  console.log('-- Auto-generated by backfill_photo_dimensions.mjs');
  console.log('-- Apply on production: mysql -u bcc_v3_app -p<pass> bcc_v3');
  console.log('');
  sqls.forEach(s => console.log(s));
  process.stderr.write(`\n${sqls.length} UPDATE statements generated.\n`);
}

main().catch(err => { console.error(err); process.exit(1); });
